site_name: PartyRent
site_description: Repositório do Grupo 7 da disciplina Arquitetura e Desenho de Software
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G7_-AluguelKitsFesta

theme:
    name: material
    logo: assets/logoheader-removebg-preview.png
    language: pt
    features:
        - navigation.tabs
        - header.autohide
    font:
    text: Sora

hide:
    - toc

extra_css:
    - assets/extra.css

nav:
    - Home: index.md
    - Apresentações:
          - Apresentação 1: 'Apresentacoes/apresentacao1.md'
    - 1. Base:
          - 1.1 Projeto Não Orientado a Abordagem Específicas:
                - Design Sprint: 'Base/Metodologia/design_sprint.md'
                - Pré-rastreabilidade:
                      - 5W2H: 'Base/Pre-rastreabilidade/5W2H.md'
                      - Causa e Efeito: 'Base/Pre-rastreabilidade/Causa&Efeito.md'
                      - Rich picture: 'Base/Pre-rastreabilidade/Richpicture.md'
                - Elicitação:
                      - Brainstorming: 'Base/Elicitacao/Brainstorm.md'
                      - Estimativas: 'Base/Elicitacao/Estimativas.md'
                      - Léxico: 'Base/Elicitacao/Lexico.md'
                      - Storyboard: 'Base/Elicitacao/Storyboard.md'
                - Priorização:
                      - MoSCoW: 'Base/Priorizacao/Moscow.md'
                      - First Thing First: 'Base/Priorizacao/FtF.md'
                - Prototipação:
                      - Protótipo: 'Base/Prototipo/Prototipo.md'
          - 1.2 Processos/Metodologias/Abordagens:
                - Metodologias: 'Base/Metodologia/metodologia.md'
                - Diagramas BPMN: 'Base/Metodologia/diagramas_BPMN.md'
          - 1.3 Extras:
                - Documento de Visão: 'Base/Extras/documento_de_visao.md'
                - Horários disponíveis: 'Base/horarios/Horario_disponibilidade.md'
                - Politicas do Repositório: 'Base/Extras/PoliticasRepositorio.md'
    - 2. Modelagem:
          - 2.1 Projeto Orientado a Abordagens Tradicionais:
                - Notação UML - Diagramas Estáticos:
                      - Diagrama de Classes: 'modelagem/diagrama_de_classes.md'
                      - Diagramas de Componentes: 'modelagem/diagramacomponentes.md'
                - Notação UML - Diagramas Dinâmicos:
                      - Diagramas de: ''
                      - Diagrama de Estado: 'modelagem/diagramadeestados.md'
                - Extras:
                      - Identidade Visual: 'modelagem/identidadevisual.md'
      #   - 3. Padrões de Projeto: ''
      #   - 4. Arquitetura de Software e Reutilização: ''

features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

plugins:
    - search
    - awesome-pages
