site_name: PartyRent
site_description: Repositório do Grupo 7 da disciplina Arquitetura e Desenho de Software
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G7_-AluguelKitsFesta

theme:
    name: material
    language: pt
    features:
        - navigation.tabs
        - header.autohide
    font:
    text: Sora

hide:
    - toc

nav:
    - Documentação do Projeto:
          - Home: index.md
          - Apresentações: ''
          - 1. Base:
                - Pré-rastreabilidade:
                      - 5W2H: 'Pre-rastreabilidade/5W2H.md'
                      - Causa e Efeito: 'Pre-rastreabilidade/Causa&Efeito.md'
                      - Rich picture: 'Pre-rastreabilidade/Richpicture.md'
                - Elicitação:
                      - Brainstorming: 'Elicitacao/Brainstorm.md'
                      - Estimativas: 'Elicitacao/Estimativas.md'
                      - Léxico: 'Elicitacao/Lexico.md'
                      - Storyboard: 'Elicitacao/Storyboard.md'
                - Priorização:
                      - MoSCoW: 'Priorizacao/Moscow.md'
                      - First Thing First: 'Priorizacao/FtF.md'
                - Prototipação:
                      - Protótipo: 'Protótipo/Protótipo.md'
                   - Processos/Metodologias:
                      - Metodologias: 'Metodologia/metodologia.md'
                      - Design Sprint: 'Metodologia/design_sprint.md'
                      - Diagramas BPMN: 'Metodologia/diagramas_BPMN.md'
                - Extras:
                      - Documento de Visão: 'Extras/documento_de_visao.md'
                      - Horário disponiveis: 'horarios/Horario_disponibilidade.md'
                      - Politicas do Repositorio: 'Extras/PoliticasRepositorio.md'
          #   - 2. Modelagem: ''
          #   - 3. Padrões de Projeto: ''
          #   - 4. Arquitetura de Software e Reutilização: ''

features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

plugins:
    - search
    - awesome-pages
